var namespace_event_master_1_1_web_1_1_services_1_1_api_dtos =
[
    [ "UserLoginRequest", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_user_login_request.html", null ],
    [ "UserRegisterRequest", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_user_register_request.html", null ],
    [ "AuthResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_auth_response.html", null ],
    [ "MeResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_me_response.html", null ],
    [ "UpdateProfileRequest", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_update_profile_request.html", null ],
    [ "ChangePasswordRequest", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_change_password_request.html", null ],
    [ "ApiOperationResult", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_api_operation_result.html", null ],
    [ "DashboardBookingCardDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_dashboard_booking_card_dto.html", null ],
    [ "BookingDetailsDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_booking_details_dto.html", null ],
    [ "CancelRefundResponseDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_cancel_refund_response_dto.html", null ],
    [ "BookingCreateRequestDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_booking_create_request_dto.html", null ],
    [ "BookingResponseDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_booking_response_dto.html", null ],
    [ "EventOccurrenceDetailsResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_event_occurrence_details_response.html", null ],
    [ "ReviewResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_review_response.html", null ],
    [ "ReplyResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_reply_response.html", null ],
    [ "ReviewEligibilityResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_review_eligibility_response.html", null ],
    [ "OrganizerEventListItemDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_organizer_event_list_item_dto.html", null ],
    [ "OrganizerEventOccurrenceDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_organizer_event_occurrence_dto.html", null ],
    [ "OrganizerCreateEventSeriesRequestDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_organizer_create_event_series_request_dto.html", null ],
    [ "OrganizerCreateOccurrenceDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_organizer_create_occurrence_dto.html", null ],
    [ "OrganizerCreatedEventSeriesResponseDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_organizer_created_event_series_response_dto.html", null ],
    [ "VenueResponseDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_venue_response_dto.html", null ],
    [ "OrganizerPendingReviewDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_organizer_pending_review_dto.html", null ],
    [ "ReplyCreateRequestDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_reply_create_request_dto.html", null ],
    [ "PaymentCreateRequestDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_payment_create_request_dto.html", null ],
    [ "PaymentResponseDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_payment_response_dto.html", null ],
    [ "BookingFinalizeResponseDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_booking_finalize_response_dto.html", null ],
    [ "ReviewCreateRequestDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_review_create_request_dto.html", null ],
    [ "UpcomingEventResponse", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_upcoming_event_response.html", null ],
    [ "OccurrenceSummaryDto", "class_event_master_1_1_web_1_1_services_1_1_api_dtos_1_1_occurrence_summary_dto.html", null ]
];